### ISSUE TITLE
Unable to Share Photos with Other users

### ISSUE THREAD

**Issue by nikhilhurule** [LibrePhotos/librephotos#697] opened 2022-12-15 21:30 UTC
I have more than 10k+ photos in my library and want to share them with other Users but when i select all photos and try to  share not able to press the share button . is there any limit to No. of photos sharing

**Comment by derneuere** [comment] 2023-01-22 14:42
I think that's a duplicate of #715 Right now we only load 100 images at a time and have to implement new endpoints for that.

**Closed as completed by derneuere** 2023-01-22 14:42 UTC
Labels: bug
