### ISSUE TITLE
Blank/console errors when viewing generated events

### ISSUE THREAD

**Issue by voarsh2** [LibrePhotos/librephotos#244] opened 2021-05-01 15:23 UTC
## 🐛 Bug Report

* [ ] I am including my log files in zip format.
* [x] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
Ubuntu 20.4 LTS

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Docker version 19.03.8
docker-compose version 1.25.0, build unknown

### Are you running LibrePhotos on a virtual machine if so please list:
LXC/Proxmox

### How is you picture library mounted on the host (or in the virtual machine):
NFS

### Description of issue:
Viewing automatically generated albums returns a blank screen after seeing the loader icon

#### Additional Information:

Chrome console:
```

:3000/api/jobs/?page_size=10&page=undefined:1 Failed to load resource: the server responded with a status of 404 (Not Found)
34menubars.js:312 /unknown_user.jpg
:3000/api/rqavailable/:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
74menubars.js:312 /unknown_user.jpg
2react-dom.production.min.js:209 Invariant Violation: A <Router> may have only one child element
    at r (http://192.168.100.28:3000/static/js/main.967d17a9.js:1:376384)
    at t.componentWillMount (http://192.168.100.28:3000/static/js/main.967d17a9.js:1:461936)
    at hn (http://192.168.100.28:3000/static/js/main.967d17a9.js:1:1104561)
    at sr (http://192.168.100.28:3000/static/js/main.967d17a9.js:1:1118684)
    at Nu (http://192.168.100.28:3000/static/js/main.967d17a9.js:1:1186164)
    at to (http://192.168.100.28:3000/static/js/main.967d17a9.js:1:1146342)
    at Qr (http://192.168.100.28:3000/static/js/main.967d17a9.js:1:1146267)
    at qr (http://192.168.100.28:3000/static/js/main.967d17a9.js:1:1143180)
    at http://192.168.100.28:3000/static/js/main.967d17a9.js:1:1099764
    at t.unstable_runWithPriority (http://192.168.100.28:3000/static/js/main.967d17a9.js:1:1195430)
br @ react-dom.production.min.js:209
205:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by derneuere** [comment] 2021-05-04 07:09
Duplicate of #184

**Closed as completed by derneuere** 2021-05-04 07:09 UTC
Labels: bug
