### ISSUE TITLE
Unraid template

### ISSUE THREAD

**Issue by guim31** [LibrePhotos/librephotos#243] opened 2021-05-01 12:39 UTC
Would it be possible to create an Unraid template ?
It would help lots of people installing librephotos...!
I have to admit I'm not able to install it the right way on my Unraid server.
Or maybe just a tutorial to help people like me ?

Thanks for all your work !

**Comment by tomamplius** [comment] 2021-05-01 16:11
Unraid server support docker image?
https://wiki.unraid.net/Manual/Docker_Management

**Comment by guim31** [comment] 2021-05-02 09:51
@tomamplius I'm not sure I understand your question.. (bad english sorry).
Unraid handles docker really well, docker-compose also.
But in a vast majority of applications it uses a template (xml format file if I'm not wrong) to help container deployement. So it's even easyier to "preconfigure" the containers to link them / fill the correct informations in the right env variable, etc..

**Comment by aryanakh** [comment] 2021-05-12 23:47
I can make one. I have experience making docker templates for Unraid. I just found this project and it looks incredibly promising! Currently it looks like there is no dockerhub image (unless reallibrephotos/librephotos) is the legit dockerhub but I cannot confirm that. Also it appears to have a front end and a back end. Once I start to better understand the requirements here I would love to test out using librephoto's myself!

**Comment by ragaimeena** [comment] 2021-06-14 19:09
> I can make one. I have experience making docker templates for Unraid. I just found this project and it looks incredibly promising! Currently it looks like there is no dockerhub image (unless reallibrephotos/librephotos) is the legit dockerhub but I cannot confirm that. Also it appears to have a front end and a back end. Once I start to better understand the requirements here I would love to test out using librephoto's myself!

any updates on this?

**Comment by Coedy** [comment] 2022-02-21 13:29
Another bump for this.
I've seen the guidance on the docs: https://docs.librephotos.com/1/unraid/
But I'm a firm believer in "if you don't know what you are doing, don't paste things into a terminal". 
I am a Docker & Unraid newbie so am at a dead end. 

An install option under the Community Application/APPS header of Unraid would be incredibly useful for other newbies like myself. Especially when the UI of LibrePhotos (at least on the demo) has so much plain English guidance on how to use it - it looks really user friendly.

**Comment by jeremytodd1** [comment] 2022-02-22 02:41
> I can make one. I have experience making docker templates for Unraid. I just found this project and it looks incredibly promising! Currently it looks like there is no dockerhub image (unless reallibrephotos/librephotos) is the legit dockerhub but I cannot confirm that. Also it appears to have a front end and a back end. Once I start to better understand the requirements here I would love to test out using librephoto's myself!

Could we get an update? We would definitely appreciate a template on the Community Apps page for this.

**Comment by AzAel76** [comment] 2022-03-09 03:30
Absolutely would love to see this

**Comment by derneuere** [comment] 2022-05-09 18:08
I cannot do this as I do not have an unraid system. Follow this guide [here](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084), send me the xml and then I can write the admin. reallibrephotos/singleton is the correct dockerhub image for the single docker image.

**Comment by derneuere** [comment] 2022-08-11 09:17
Duplicate of #276

**Closed as completed by derneuere** 2022-08-11 09:17 UTC
Labels: enhancement
