### ISSUE TITLE
"similar images" not clickable

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#1141] opened 2024-01-24 22:51 UTC
When opening the details of a photos, some of them will have a "similar images" section near the bottom.
Expected behavior: clicking the image thumbnail will open the image

Current behavior, clicking the image thumbnail does nothing

Running docker on x86

**Comment by derneuere** [comment] 2024-01-31 12:11
Duplicate of #265 :)

**Closed as completed by derneuere** 2024-01-31 12:11 UTC
Labels: bug
