### ISSUE TITLE
Librephotos  + UhuruPhotos app

### ISSUE THREAD

**Issue by mxm199** [LibrePhotos/librephotos#916] opened 2023-07-10 08:00 UTC
Good day everyone!

Please tell me, in the instruction for creating a token, secret scopes are marked that must be selected -

![scopes0](https://github.com/LibrePhotos/librephotos/assets/133875469/bd83a311-afbd-4535-8626-d23847224aa2)

But on the mapbox site, when creating a token, there are no such secret scopes. What secret scopes should be used?

![scopes](https://github.com/LibrePhotos/librephotos/assets/133875469/dcef9174-b912-4915-88ac-1a13cf333c35)

Another question is whether it makes sense in the token settings to specify the url of the site where my librephotos?

**Comment by martijn-gr** [comment] 2023-07-25 05:23
I believe this is not a bug but an inconsistency in the documentation.

I am not familiar with the Mapbox website and service, but I discovered the same.
Using the default public token from Mapbox, or creating a dedicated one for your LibrePhoto install will work with the software. 
One does not seem to need the Secret scope "styles.list", all the other options are in the Public scope and enabled by default for every api key.

@mxm199 does this help you?

**Comment by mxm199** [comment] 2023-07-25 12:40
I agree, not a bug)
Why did I open a question about the token, since the UhuruPhotos application does not display photos on the Photo Map, and this is a very convenient feature. I thought it might be because of the Mapbox token. The developer of the application could not help in any way, but tried to do it.
Maybe someone here can suggest what could be the problem. Librephotos is installed in docker, through the web interface (locally and via the Internet (nginx)) everything works properly, and UhuruPhotos works fine, except for Photo Map.

**Comment by martijn-gr** [comment] 2023-07-25 14:18
HI @mxm199 

I don't know about UhuruPhotos.
My primary question would be:
Does the Map function work in your LibrePhoto install? If so, I would assume it has something to do with the (to me) unknown UhuruPhotos app. I do see it would integrate but this issue should be related to the LibrePhotos  and Mapbox integration.
Not about an integration with a thirdparty app.
Otherwise the description of the issue is incorrect.

--Edit--
I just installed the UhuruPhotos app myself, but the latest version just draws the photos from my local cache on the map.
It does take some time, as it has to fetch the EXIF data for each photo once and cache it in the app, but it works for me.
I do not have the feeling this functionality is depending on the LibrePhotos server components.

**Comment by mxm199** [comment] 2023-07-25 14:39
Local cache, or photos on the phone? The program displays photos on the phone on the Photo map, but those from the Librephotos server do not, although I collected the cache of photos from Librephotos in the program completely.
But thanks for the help, although this discussion is probably not for the Librephotos branch.

**Comment by martijn-gr** [comment] 2023-07-25 14:52
> Local cache, or photos on the phone? The program displays photos on the phone on the Photo map, but those from the Librephotos server do not, although I collected the cache of photos from Librephotos in the program completely. But thanks for the help, although this discussion is probably not for the Librephotos branch.

I noticed the same, local photos do display on the map, but those from the server do not.
My main question would be does your LibrePhotos server show some of them on the map, if yes, it is with the app, if no, i would suggest to keep this going but with more information.

Otherwise one of the devs or the repo owner can close it.

**Comment by mxm199** [comment] 2023-07-26 09:28
In the web interface of Librephotos, the map is displayed correctly, all photos with a geotag have exif metadata.
But if you look at the log of UhuruPhotos , you can see errors, I will give a link to my post in the UhuruPhotos [topic](https://github.com/savvasdalkitsis/uhuruphotos-android/issues/334#issuecomment-1632057530). It's just strange, but no one else complains about this problem :)
Maybe the developer Librephotos or colleagues will tell us something...

**Comment by derneuere** [comment] 2023-07-28 07:14
Did you rescan your images after adding the mapbox key?

**Comment by mxm199** [comment] 2023-07-28 07:50
Yes, several times

**Comment by derneuere** [comment] 2024-03-24 12:51
We refactored the whole process, so this issue is probably fixed :)

**Closed as completed** 2024-03-24 12:51 UTC
Labels: bug
