### ISSUE TITLE
Version information in the frontend

### ISSUE THREAD

**Issue by Seneliux** [LibrePhotos/librephotos#433] opened 2022-01-28 11:11 UTC
It is good to add some version information to the frontend. Including backend / frontend version.

Now it is hard to track updates, versions, etc.

**Comment by MatthewBraun** [comment] 2022-02-27 02:40
It would be great if there was an "About" page under the menu that contains "logout" "settings" "admin area" On that page it would include the versions along with a link to the Github and possibly a list of the most recent versions. Maybe even have a "bug report" instruction page for ease of reporting issues.

**Comment by 5m4u66y** [comment] 2022-11-15 15:02
Duplicate of issue #575

**Closed as completed** 2022-11-15 17:50 UTC
Labels: enhancement
