### ISSUE TITLE
Switching user (logout/login) shows previous user's photos, until refresh

### ISSUE THREAD

**Issue by varet80** [LibrePhotos/librephotos#687] opened 2022-11-30 22:32 UTC
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [x] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
I am facing an issue with my Installation:
I have two users user1 and varet!

User1 has 0 photos
Varet has 11000 photos.

When I logout from one and login to the other. Until I refresh! I still can see the other user's photos! or none... once I refresh they dissapear! I need help to understand what I am doing wrong. (some cookie mistake on setup)
Installation:Docker and in k8s

The current photos show: Login to user1, logout, login to varet, refresh varet

if After logout, I refresh the page. this does not happen. I suspect during logout. some session is not cleanedup?

## 🔁 How can we reproduce it:

The current photos show: Login to user1, logout, login to varet, refresh varet
if After logout, I refresh the page. this does not happen. I suspect during logout. some session is not cleanedup?

## Please provide additional information:
- 💻 Operating system: Ubuntu
- ⚙ Architecture (x86 or ARM): amd64 
- 🔢 Librephotos version: 2022w45 (happened always
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: 2022w45
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): nfs
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):  nope
- 
![image](https://user-images.githubusercontent.com/4048920/204922461-520b7705-e006-438f-a87a-417cbe370553.png)
![image](https://user-images.githubusercontent.com/4048920/204922476-feb37ddf-72fb-444e-a42b-d124653484ab.png)
![image](https://user-images.githubusercontent.com/4048920/204922487-10d5ceeb-48c6-4954-8ebd-6170cb1b290e.png)

**Comment by Nerodacles** [comment] 2022-12-01 05:11
Duplicate of #453

**Comment by derneuere** [comment] 2022-12-06 21:36
This is fixed now :)

**Closed as completed by derneuere** 2022-12-06 21:36 UTC
Labels: bug
