### ISSUE TITLE
No such file or directory /var/lib/postgresql/data.

### ISSUE THREAD

**Issue by andrewrohde** [LibrePhotos/librephotos#157] opened 2021-02-02 01:40 UTC
Getting the following error starting a new instance. All directories are created and empty. Hard to tell, but is it saying my local librephotos_data directory I mount through docker-compose volumes does not exist or /var/lib/postgresql/data within the container does not exist?

```
Creating network "librephotos_default" with the default driver
Creating librephotos-proxy    ... done
Creating librephotos-db       ... error
Creating librephotos-frontend ...
Creating librephotos-redis    ...

ERROR: for librephotos-db  Cannot start service librephotos-db: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/containers/librephotos/librephotos_data\\\" to rootfs \\\"/var/lib/docker/overlay2/c247022c0b455c472adcda5921ff7da22f9699Creating librephotos-frontend ... done
Creating librephotos-redis    ... done

ERROR: for librephotos-db  Cannot start service librephotos-db: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/containers/librephotos/librephotos_data\\\" to rootfs \\\"/var/lib/docker/overlay2/c247022c0b455c472adcda5921ff7da22f96999ae4545e7f6274a6447dbc865b/merged\\\" at \\\"/var/lib/docker/overlay2/c247022c0b455c472adcda5921ff7da22f96999ae4545e7f6274a6447dbc865b/merged/var/lib/postgresql/data\\\" caused \\\"no such file or directory\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
```

.env volumes
```
# The location where you would like to store the log files. The full path must exist as it will not be created for you. 
logLocation=/containers/librephotos/librephotos_logs/

# Protected media directory. This is where we store some files like the thumbnails of your images. 
proMedia=/containers/librephotos/librephotos_media

# Where shall we store the cache files. 
cachedir=/containers/librephotos/librephotos_cache

# Where shall we store the database. 
dbLocation=/containers/librephotos/librephotos_data`
```

**Comment by DigitalWarrior** [comment] 2021-02-02 04:15
@andrewrohde 
What OS and version are you running?
What is your docker version & docker compose version?

**Comment by andrewrohde** [comment] 2021-02-02 12:16
@DigitalWarrior
OS: Ubuntu 20.04.2
Docker: 19.03.8, build afacb8b7f0
Docker Compose: 1.25.0

**Comment by andrewrohde** [comment] 2021-02-02 21:47
So the problem is I'm using an NFS mount for all the data directories which are on a local server. If I select locations within the local VM it works. Is there a way to get postgres to work when the docker volumes are a mounted NFS directory?

Had this same issue on another project where MySQL didn't like a SMB mounted directory as a docker volume. Once it was changed to an NFS mount MySQL worked. postgres doesn't like the NFS mount.

**Comment by derneuere** [comment] 2021-02-02 22:03
Maybe this tutorial from a similar product works?
https://docs.photoprism.org/getting-started/faq/#how-can-i-mount-network-shares-with-docker

**Comment by derneuere** [comment] 2022-03-27 11:16
duplicate of #167

**Closed as completed by derneuere** 2022-03-27 11:16 UTC
Labels: question
