### ISSUE TITLE
Adding translations

### ISSUE THREAD

**Issue by lonelyhero77** [LibrePhotos/librephotos#291] opened 2021-07-07 15:06 UTC
**Describe the enhancement you'd like**
Adding translations would be a great idea for this project.

**Describe why this will benefit the LibrePhotos**
If the translations are added, there will be a lot of people who would like to contribute this project. 

**Additional context**
Since it is a open-sourced project, I think using online translate platform such as crowdin, weblate etc to translate is great idea.

**Comment by derneuere** [comment] 2021-07-26 08:25
Duplicate of #116

**Closed as completed by derneuere** 2021-07-26 08:25 UTC
Labels: enhancement
