### ISSUE TITLE
Drop-down menu judders

### ISSUE THREAD

**Issue by Bessie** [LibrePhotos/librephotos#965] opened 2023-07-23 07:55 UTC
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [ ] ❌ I have looked for similar issues (including closed ones)
* [x] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Looking at demo 1 on a windows system with edge there are instances where the right-hand dropdown menu judders around.

## 🔁 How can we reproduce it:

Using windows and the edge browser go to the "things" album, select a thing, click on the three dots on the right-hand side of the page in the grey bar - the menu bar jumps around. (it doesn't do it for me on the main photos page, or in people albums, but it also does it in "my albums")

![chrome-capture-2023-6-23](https://github.com/LibrePhotos/librephotos/assets/62910255/d7b87c11-7381-45ac-840c-1fc1d9845a37)

**Comment by derneuere** [comment] 2023-07-26 09:31
Cant seem to reproduce this on demo2, which is the dev version. I bumped a lot of dependenices, which could explain why it's now fixed. Would be nice if you could test it :)

**Comment by derneuere** [comment] 2023-08-03 15:16
You need exactly one image in a thing category in order for the menu to judder.

**Comment by derneuere** [comment] 2024-05-20 09:17
Looks like this was fixed along the way :)

**Closed as completed by derneuere** 2024-05-20 09:17 UTC
Labels: bug
