### ISSUE TITLE
.

### ISSUE THREAD

**Issue by shaun-ba** [LibrePhotos/librephotos#479] opened 2022-04-01 07:25 UTC
.

**Comment by polaroidkidd** [comment] 2022-04-01 12:11
What do you mean when you say "terminating beforehand"?

Typically all client requests go through the proxy container (in my case nginx with Letsencrypt certs) and are then passed on within the server network without any SSL.

**Comment by shaun-ba** [comment] 2022-04-04 09:36
.

**Comment by polaroidkidd** [comment] 2022-04-04 11:22
> SSL terminates on my own proxy server and is then forwarded to librephotos

This is the standard setup and should work as advertised.

> they are blurred out

that's really weird. Can you show some logs of the network tab and if the console is throwing any errors?

Which version are you using? Can you try the `dev` tags and see if that resolves the issue?

**Comment by shaun-ba** [comment] 2022-04-04 13:40
.

**Comment by polaroidkidd** [comment] 2022-04-04 13:48
Ah, ok. That looks like an error I merged recently. I'm on the move right now but I'll get back tonight.

Regarding the nginx config, there isn't anything special. In the librephotos-docker repo, there's a proxy folder with an nginx config. I used this one to integrate it in my existing services/reverse proxy (which also runs nginx).


Here's the nginx config:
https://github.com/LibrePhotos/librephotos-docker/blob/main/proxy/nginx.conf#L14

I'll look into the API issue tonight.

**Comment by shaun-ba** [comment] 2022-04-04 13:51
.

**Comment by polaroidkidd** [comment] 2022-04-05 19:03
its a crazy week at work atm and I'm afraid that I won't have the time to look into this more closely until the weekend, I hope that's not too late for you.

**Comment by polaroidkidd** [comment] 2022-04-05 20:31
Right, so I had a quick look on my selfhosted instance and I can't reproduce the error. Are you also running the image tag `509200069a42` ?

It could also be a side effect of me migrating some of the API over to rtk-query recently. Does the error persist when you logout, clear all cookies and delete the local-storage entries?

**Comment by shaun-ba** [comment] 2022-04-06 07:49
.

**Comment by polaroidkidd** [comment] 2022-04-06 13:57
ah, you're running with the `latest` tags. This issue might have already been resolved. Could you try running it with the `dev` tag?

**Comment by derneuere** [comment] 2022-04-13 17:56
Not sure, if you ever got around to changing the tag, but the new release is also online which should fix this issue :)

**Comment by polaroidkidd** [comment] 2022-07-25 20:26
@shaun-ba  are you still experiencing this or can we close this?

**Comment by hardwareadictos** [comment] 2023-06-16 16:19
Having the exact same issue using my own reverse proxy (Nginx Proxy Manager), previews blurried and lots on unauthorized log messages everywhere doing anything:

![image](https://github.com/LibrePhotos/librephotos/assets/20403906/ebffc2c7-2774-41f6-87c9-9340d8926d91)

![image](https://github.com/LibrePhotos/librephotos/assets/20403906/88ff192f-e72b-4fd5-aaa8-3e899b5ed3ea)

![image](https://github.com/LibrePhotos/librephotos/assets/20403906/e49e407d-cc5c-449b-88d8-c25d66f8aed8)

**Closed as completed** 2023-06-17 10:34 UTC

**Comment by derneuere** [comment] 2023-06-17 10:36
The error is pretty clear. It can't find the thumbnail, which means, that you either played around with the proxy of librephotos, and it does not redirect to the protected_media folder anymore, or you did not set up the data folder properly.

**Comment by hardwareadictos** [comment] 2023-06-20 09:56
> os, and it does not redirect to the protected_media folder anymore, or you did not set up the data folde

True! Just managed to fix it, i didn't realise that protected_media was mounted also by proxy, and as i mount this volume on a NFS share i forgot to change proxy mounting path also... Thanks for the help :)
