### ISSUE TITLE
Traversing symbolic links

### ISSUE THREAD

**Issue by hoppushoppard** [LibrePhotos/librephotos#148] opened 2021-01-24 23:31 UTC
Hi,
I've set myPhotos to `/home/hopp/Photos`

inside I have a symbolic link to different folder
```
hopp@sleipnir ~/Photos $ ls -la Photos-on-Second
lrwxrwxrwx 1 hopp hopp 21 Jan 24 20:00 Photos-on-Second -> /media/second/Photos/
```
But UI where I can pick a folder is not listing it.
> Admin Area > Users > admin > Scan Directory > data

I can see there all folders, but not a symbolic link.

I'm not very good pythonist, but I believe that in file `dev/api/directory_watcher.py`
a method called `def walk_directory(directory, callback):` (line 174) walks through directories.
It uses  `os.path.isdir(path)` which returns true for symbolic link "pointing" on folder.

So I'm assuming I'm doing something wrong.

Would you be so kind for some guidence ?

Is it possible to set multiple "Scan Directory" entries ?
I think, because of docs
> Only the admin user can change the "scan directory" of the users, including the admin itself.

there could be only one path ?

**Comment by derneuere** [comment] 2021-01-25 09:03
Symbolic links cannot be currently used in the selection screen, but will be scanned. It is related to #98 and #136
You cannot select multiple paths per user at the moment see #123 , but you can set one path per user.

**Comment by hoppushoppard** [comment] 2021-01-27 23:10
I understood your reply, that even though I can't select in UI, the symbolic link is traversed and scaned.

I've placed a symbolic link to a folder into my `/data/` path
`lrwxrwxrwx   1 hopp hopp        10 Jan 27 23:10  Testing_Traversing_Symbolic_Links -> /tmp/test/`
I have three photos there with timestamp 2021.01.27 (yyyy.mm.dd)
```
hopp@sleipnir ~/Photos $ ls /tmp/test/
'2021-01-27 07.54.00.jpg'  '2021-01-27 10.00.07.jpg'  '2021-01-27 10.00.59.jpg'
```

I went to Dashboard > Library and pushed 'Scan photos (file system)'
I've waited for job Scan Photos to finish in Admin Area .

In `Photos  > With Timestamp` there are **no** photos with timestamp 2021.01.27.

Is there any log I can go through ?

Please advice ...

**Comment by derneuere** [comment] 2021-01-28 09:24
The timestamp has to be in the exif data for now. Specifically Exif DateTimeOriginal. Your photos are under Photos > Without timestamp. Maybe I will enable the filename parser again, but will make it an option.

**Comment by derneuere** [comment] 2022-08-17 09:30
Duplicate of #169

**Closed as completed by derneuere** 2022-08-17 09:30 UTC
Labels: question
