### ISSUE TITLE
Images show up as 0x0 in size for JXL

### ISSUE THREAD

**Issue by scepterus** [LibrePhotos/librephotos#862] opened 2023-05-19 14:21 UTC
# 🐛 Bug Report

* [ ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [X] ❌ I have looked for similar issues (including closed ones)
* [X] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
This may be related to a previous issue:
https://github.com/LibrePhotos/librephotos/issues/845
But some photos are scanned with 0x0 as their size, even though when I look at their info in IrfanView for example or MediaInfo, they show up correctly. Same for Windows properties.

## 🔁 How can we reproduce it:
No idea, Perhaps I can provide you with a photo as a test.

## Please provide additional information:
- 💻 Operating system:  TrueNAS Scale
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: Latest
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: latest
- 📁 How is your picture library mounted (Local file system (Type), NFS, SMB, etc.): direct mount
![image](https://github.com/LibrePhotos/librephotos/assets/56637330/bf32ba4a-2ceb-4b72-997e-9c0614013f1e)

**Comment by scepterus** [comment] 2023-05-19 14:24
Also related to:
https://github.com/LibrePhotos/librephotos/issues/863
where these images do not get a time stamp, even though some of them have the time portion in the file name.

**Comment by derneuere** [comment] 2023-05-19 22:45
We use exiftool to read and write exif data. It would be great if you could use that to read out the data and provide a list with the attributes. It could be that somehow there are multiple heights and widths, but we skip that, because we assume it's one value.

Furthermore, it's weird that it happens to so many images. To me, it looks like it maybe could be a file permission issue.

I also don't see this issue on demo2, which indicates that it's a file / system specific issue.

EDIT: It would also be helpful if you could look into the ownphotos.log file in your system. There could be an error there.

**Comment by scepterus** [comment] 2023-05-20 18:27
I found the issue then. exiftool reports unknown file type. The file type is jxl, but that would only explain the dimensions, not the date parsing. Or maybe it would, since when I tried to add options to the command it errored out completely as opposed to just giving me the basic data and saying unknown file type.

Not all images have exif data, the ones that don't should probably use identify filename. That would return:
Container type resolution bit depth and more.

I have not looked yet, do you have a check to see if the file has exif data?
If not, I think the way to do it is to first check if there is exif data for the file, if that fails or there isn't data on that, use identify as a fallback for the information.

**Comment by derneuere** [comment] 2023-05-22 07:24
Could you try out the latest version by directly downloading it from the website? https://exiftool.org/index.html It looks like there were a couple of patches regarding jxl in the last couple of releases. If that fixes the unknown file type, I will then bump the version in the base image.

ExifTool falls automatically back on the base information as long as it knows the file type.

**Comment by scepterus** [comment] 2023-05-22 17:36
Just tested that, it does not return dimensions when I do -ImageSize. it does recognize the format though.

**Comment by derneuere** [comment] 2023-05-22 17:38
That sounds promising! We look at the ExifTags ImageHeight and ImageWidth

**Comment by scepterus** [comment] 2023-05-22 18:39
Yeah those are the ones I tested, they return nothing. do we  just wait for exif to update the tool to reach those correctly, or do you want to implement the fallback I wrote in the `identify ` command?

**Comment by derneuere** [comment] 2023-05-24 07:45
I downloaded a couple of jxl files to recreate your issue: https://github.com/libjxl/libjxl/issues/716#issuecomment-940151944

The height is showing up just fine:
![image](https://github.com/LibrePhotos/librephotos/assets/6658807/a7e39d04-e134-4334-bd6c-5e6d3d1e2e7d)

I think I need more information about your jxl files. What kind are they, how were they encoded, which device took them etc. This is probably an edge case, which is missing in exiftool and I would like to report the issue upstream.

It would also be interesting to return all exiftags for one jxl file with exiftool. Maybe your file uses a different tag for height and width.

**Comment by scepterus** [comment] 2023-05-24 11:35
I have the exact command that I used to convert these.
it's:
`cjxl -q 100 -e 9 "$image_file" "../Converted/${image_file%.*}.jxl"`
then I:
`touch -r "$image_file" "../Converted/${image_file%.*}.jxl"`

You can use these commands on any jpegs or png. I think the difference is these were sent via whatsapp or other IM app, and that strips the original info from them.

**Comment by derneuere** [comment] 2023-06-04 08:40
Can reproduce it, when I converted it with cjxl. Will look into what causes this.

**Comment by derneuere** [comment] 2023-06-04 09:23
Reported the error upstream: https://exiftool.org/forum/index.php?topic=14895.0

**Comment by scepterus** [comment] 2023-06-09 06:35
https://exiftool.org/forum/index.php?PHPSESSID=8d92131dbdbafcbac28204e7fd391fac&topic=14840.0
Seems there's a fix that can be tested.

**Comment by scepterus** [comment] 2023-06-09 11:44
Can confirm, Image-Size now returns the correct dimensions. As for dates, I have yet to test.

**Comment by scepterus** [comment] 2023-06-09 14:16
After updating manually, sizes are fixed. Dates are still not.

**Comment by derneuere** [comment] 2023-06-09 17:58
There is now a new base image, with the latest exiftool and brotli installed. The dev backend image should be available in 30 minutes and this fix will be in the next release.

**Closed as completed by derneuere** 2023-06-09 17:58 UTC
Labels: bug
